name: logx_example
description: Example app for LogX package
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logx:
    path: ../

flutter:
  uses-material-design: true